### ISSUE TITLE
[BUG]: There is typo in .env_sample, SERVERURL is written as SEVERURL

### ISSUE THREAD

**Issue by kantakshay** [OpenSourcePal/OpenSourcePal#12]
SERVERURL is written as SEVERURL which also needs to be corrected in following files

https://github.com/OpenSourcePal/OpenSourcePal/blob/76bc5e65c1481f6ec6b137ba740af2cb5cf26cd0/.env_sample#L3

https://github.com/OpenSourcePal/OpenSourcePal/blob/76bc5e65c1481f6ec6b137ba740af2cb5cf26cd0/src/background/index.ts#L5

https://github.com/OpenSourcePal/OpenSourcePal/blob/76bc5e65c1481f6ec6b137ba740af2cb5cf26cd0/src/popup/components/Popup.tsx#L12

https://github.com/OpenSourcePal/OpenSourcePal/blob/76bc5e65c1481f6ec6b137ba740af2cb5cf26cd0/src/utils/api.ts#L22

**Comment by Priyanshu2117** [comment]
I would like to work on this issue, please assign it to me.

**Comment by Dun-sin** [comment]
> I would like to work on this issue, please assign it to me.

You've got it, good luck
